function theRes=allLinCompMLB()
names={...
'firmValue'...
'fuhrerMoore'...
'hall1estimateBayes'...
'lesothoViegi'...
'lubikSchorfheide'...
'rosenestimateBayes'...
'simpleNeoViegi'...
};
theRes=zeros(7,2);
for ii=1:7
theRes(ii,:)=docompareMLB(names{ii});
end
end
